-- Chèn dữ liệu mới vào bảng Products với các chuỗi Unicode
INSERT INTO Products (ProductName, Description, Price, StockQuantity, Category, ImageUrl, CreatedAt, UpdatedAt) VALUES 
(N'Adapter Sạc Type C PD 20W', N'Adapter Sạc Type C PD 20W Anker PowerPort III Nano A2633', 400000, 600, N'Adapter, Cáp sạc', N'./img/Anker/Adapter_capsac/Adapter Sạc Type C PD 20W Anker PowerPort III Nano A2633.jpg', GETDATE(), GETDATE()),
(N'Tai Nghe Bluetooth True Wireless', N'Tai Nghe Bluetooth True Wireless Anker SoundCore Liberty 2 Pro A3909', 3500000, 200, N'Tai nghe', N'./img/Anker/Tai_Nghe/Tai Nghe Bluetooth True Wireless Anker SoundCore Liberty 2 Pro A3909.jpg', GETDATE(), GETDATE()),
(N'Loa Bluetooth Sony SRS-XP500', N'Loa Bluetooth Sony SRS-XP500', 1600000, 150, N'Loa', N'./img/Sony/Loa/Loa Bluetooth Sony SRS-XP500.jpg', GETDATE(), GETDATE()),
(N'Loa thanh Sony HT-S100F 120W', N'Loa thanh Sony HT-S100F 120W', 1750000, 150, N'Loa', N'./img/Sony/Loa/Loa thanh Sony HT-S100F 120W.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Bluetooth True Wireless', N'Tai nghe Bluetooth True Wireless Sony WF-C500', 2100000, 300, N'Tai nghe', N'./img/Sony/Tai_Nghe/Tai nghe Bluetooth True Wireless Sony WF-C500.jpeg', GETDATE(), GETDATE()),
(N'Tai nghe Bluetooth True Wireless Pro', N'Tai nghe Bluetooth True Wireless Sony WF-C700N', 3900000, 150, N'Tai nghe', N'./img/Sony/Tai_Nghe/Tai nghe Bluetooth True Wireless Sony WF-C700N.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Chụp Tai Sony MDR', N'Tai nghe Chụp Tai Sony MDR - ZX110AP', 1140000, 150, N'Tai nghe', N'./img/Sony/Tai_Nghe/Tai nghe Chụp Tai Sony MDR - ZX110AP.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Có Dây Sony MDR', N'Tai nghe Có Dây Sony MDR-EX15AP', 352000, 320, N'Tai nghe', N'./img/Sony/Tai_Nghe/Tai nghe Có Dây Sony MDR-EX15AP.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Có Dây Sony DMX', N'Tai nghe Có Dây Sony MDR-EX155AP', 200000, 320, N'Tai nghe', N'./img/Sony/Tai_Nghe/Tai nghe Có Dây Sony MDR-EX155AP.jpg', GETDATE(), GETDATE()),
(N'Adapter Sạc USB 18W OPPO', N'Adapter Sạc USB 18W OPPO OP92KAUH', 300000, 100, N'Adapter, Cáp sạc', N'./img/Oppo/Adapter_capsac/Adapter Sạc USB 18W OPPO OP92KAUH.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Bluetooth True Wireless', N'Tai nghe Bluetooth True Wireless OPPO ENCO Air 3 ETE31', 500000, 300, N'Tai nghe', N'./img/Oppo/Tai_nghe/Tai nghe Bluetooth True Wireless OPPO ENCO Air 3 ETE31.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Bluetooth True Wireless Pro', N'Tai nghe Bluetooth True Wireless OPPO ENCO Buds 2 ETE41', 1750000, 150, N'Tai nghe', N'./img/Oppo/Tai_nghe/Tai nghe Bluetooth True Wireless OPPO ENCO Buds 2 ETE41.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Có Dây OPPO MH151', N'Tai nghe Có Dây OPPO MH151', 250000, 170, N'Tai nghe', N'./img/Oppo/Tai_nghe/Tai nghe Có Dây OPPO MH151.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Có Dây OPPO MH320', N'Tai nghe Có Dây OPPO MH320', 250000, 170, N'Tai nghe', N'./img/Oppo/Tai_nghe/Tai nghe Có Dây OPPO MH320.jpg', GETDATE(), GETDATE()),
(N'Adapter chuyển đổi Type C', N'Adapter chuyển đổi Type C 4 in 1 Xmobile DS122F', 500000, 170, N'Adapter, Cáp sạc', N'./img/XMobile/Adapter_capsac/Adapter chuyển đổi Type C 4 in 1 Xmobile DS122F.jpg', GETDATE(), GETDATE()),
(N'Adapter Sạc Type C PD GaN 30W', N'Adapter Sạc Type C PD GaN 30W Xmobile DS230', 600000, 200, N'Adapter, Cáp sạc', N'./img/XMobile/Adapter_capsac/Adapter Sạc Type C PD GaN 30W Xmobile DS230.jpg', GETDATE(), GETDATE()),
(N'Loa Bluetooth JBL Flip 6', N'Loa Bluetooth JBL Flip 6', 2599000, 200, N'Loa', N'./img/JBL/Loa/Loa Bluetooth JBL Flip 6.jpg', GETDATE(), GETDATE()),
(N'Loa Bluetooth JBL Go Essential', N'Loa Bluetooth JBL Go Essential', 690000, 100, N'Loa', N'./img/JBL/Loa/Loa Bluetooth JBL Go Essential.jpg', GETDATE(), GETDATE()),
(N'Loa Bluetooth JBL Go 3', N'Loa Bluetooth JBL Go 3', 249000, 150, N'Loa', N'./img/JBL/Loa/Loa Bluetooth JBL Go 3.jpg', GETDATE(), GETDATE()),
(N'Loa Bluetooth JBL Partybox Encore', N'Loa Bluetooth JBL Partybox Encore', 5900000, 100, N'Loa', N'./img/JBL/Loa/Loa Bluetooth JBL Partybox Encore 2Mic.jpg', GETDATE(), GETDATE()),
(N'Pin sạc dự phòng Polymer 5000mAh', N'Pin sạc dự phòng Polymer 5000mAh Không dây Magnetic Type C 12W Anker MagGo A1611', 1150000, 400, N'Adapter, cáp sạc', N'./img/Anker/Sac_Du_Phong/Pin sạc dự phòng Polymer 5000mAh Không dây Magnetic Type C 12W Anker MagGo A1611.jpg', GETDATE(), GETDATE()),
(N'Loa Bluetooth JBL Partybox On', N'Loa Bluetooth JBL Partybox On The Go', 6390000, 55, N'Loa', N'./img/JBL/Loa/Loa Bluetooth JBL Partybox On The Go.jpg', GETDATE(), GETDATE()),
(N'Loa Bluetooth JBL Partybox 110', N'Loa Bluetooth JBL Partybox 110', 9350000, 99, N'Loa', N'./img/JBL/Loa/Loa Bluetooth JBL Partybox 110.jpg', GETDATE(), GETDATE()),
(N'Loa Bluetooth JBL Pulse 5', N'Loa Bluetooth JBL Pulse 5', 6150000, 200, N'Loa', N'./img/JBL/Loa/Loa Bluetooth JBL Pulse 5.jpg', GETDATE(), GETDATE()),
(N'Loa Bluetooth JBL Xtreme 3', N'Loa Bluetooth JBL Xtreme 3', 5700000, 300, N'Loa', N'./img/JBL/Loa/Loa Bluetooth JBL Xtreme 3.jpg', GETDATE(), GETDATE()),
(N'Loa siêu trầm JBL PASION 12SP 300W', N'Loa siêu trầm JBL PASION 12SP 300W', 9000000, 150, N'Loa', N'./img/JBL/Loa/Loa siêu trầm JBL PASION 12SP 300W.jpg', GETDATE(), GETDATE()),
(N'Loa điện karaoke JBL IRX108BT', N'Loa điện karaoke JBL IRX108BT 1000W', 9450000, 30, N'Loa', N'./img/JBL/Loa/Loa điện karaoke JBL IRX108BT 1000W.jpg', GETDATE(), GETDATE()),
(N'Loa điện karaoke JBL IRX112BT', N'Loa điện karaoke JBL IRX112BT 1300W', 9740000, 60, N'Loa', N'./img/JBL/Loa/Loa điện karaoke JBL IRX112BT 1300W.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Bluetooth Chụp Tai JBL T500', N'Tai nghe Bluetooth Chụp Tai JBL T500', 890000, 500, N'Tai nghe', N'./img/JBL/Tai_Nghe/Tai nghe Bluetooth Chụp Tai JBL T500.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Bluetooth Chụp Tai JBL 520BT', N'Tai nghe Bluetooth Chụp Tai JBL Tune 520BT', 700000, 200, N'Tai nghe', N'./img/JBL/Tai_Nghe/Tai nghe Bluetooth Chụp Tai JBL Tune 520BT.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Có Dây JBL C200 SIU', N'Tai nghe Có Dây JBL C200 SIU', 600000, 150, N'Tai nghe', N'./img/JBL/Tai_Nghe/Tai nghe Có Dây JBL C200 SIU.jpg', GETDATE(), GETDATE()),
(N'Pin sạc dự phòng 10.000 mAh', N'Pin sạc dự phòng 10.000 mAh Anker PowerCore Select A1223', 1180000, 500, N'Adapter, cáp sạc', N'./img/Anker/Sac_Du_Phong/Pin sạc dự phòng 10.000 mAh Anker PowerCore Select A1223.jpg', GETDATE(), GETDATE()),
(N'Ốp lưng Redmi 9C Nhựa dẻo', N'Ốp lưng Redmi 9C Nhựa dẻo', 40000, 250, N'Ốp Lưng', N'./img/Xiaomi/Op_lung/Ốp lưng Redmi 9C Nhựa dẻo.jpg', GETDATE(), GETDATE()),
(N'Ốp lưng Xiaomi Poco C40 Nhựa', N'Ốp lưng Xiaomi Poco C40 Nhựa', 80000, 300, N'Ốp Lưng', N'./img/Xiaomi/Op_lung/Ốp lưng Xiaomi Poco C40 Nhựa.jpg', GETDATE(), GETDATE()),
(N'Ốp lưng Xiaomi Redmi A2+ Nhựa dẻo', N'Ốp lưng Xiaomi Redmi A2+ Nhựa dẻo', 30000, 150, N'Ốp Lưng', N'./img/Xiaomi/Op_lung/Ốp lưng Xiaomi Redmi A2+ Nhựa dẻo.jpg', GETDATE(), GETDATE()),
(N'Ốp lưng Xiaomi Redmi A2 Nhựa dẻo TPU', N'Ốp lưng Xiaomi Redmi A2 Nhựa dẻo TPU JM Cons Shock', 90000, 200, N'Ốp Lưng', N'./img/Xiaomi/Op_lung/Ốp lưng Xiaomi Redmi A2 Nhựa dẻo TPU JM Cons Shock.jpg', GETDATE(), GETDATE()),
(N'Ốp lưng Xiaomi Redmi 10A Nhựa dẻo', N'Ốp lưng Xiaomi Redmi 10A Nhựa dẻo', 50000, 250, N'Ốp Lưng', N'./img/Xiaomi/Op_lung/Ốp lưng Xiaomi Redmi 10A Nhựa dẻo.jpg', GETDATE(), GETDATE()),
(N'Ốp lưng Xiaomi Redmi 12 Silicone', N'Ốp lưng Xiaomi Redmi 12 Silicone JM Candy', 70000, 350, N'Ốp Lưng', N'./img/Xiaomi/Op_lung/Ốp lưng Xiaomi Redmi 12 Silicone JM Candy.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Bluetooth True Wireless', N'Tai nghe Bluetooth True Wireless Xiaomi Redmi Buds 4 Active', 540000, 100, N'Tai nghe', N'./img/Xiaomi/Tai_Nghe/Tai nghe Bluetooth True Wireless Xiaomi Redmi Buds 4 Active.jpg', GETDATE(), GETDATE()),
(N'Tai nghe Bluetooth TWS', N'Tai nghe Bluetooth TWS Xiaomi Redmi Buds 4 Lite', 440000, 300, N'Tai nghe', N'./img/Xiaomi/Tai_Nghe/Tai nghe Bluetooth TWS Xiaomi Redmi Buds 4 Lite.jpg', GETDATE(), GETDATE()),
(N'Adapter Sạc Type C PD 25W', N'Adapter Sạc Type C PD 25W Samsung EP-TA800N', 150000, 100, N'Adapter, cáp sạc', N'./img/Samsung/Adapter_capsac/Adapter Sạc Type C PD 25W Samsung EP-TA800N.jpg', GETDATE(), GETDATE()),
(N'Adapter Sạc Type C 15W Samsung', N'Adapter Sạc Type C 15W Samsung EP-T1510N', 100000, 150, N'Adapter, cáp sạc', N'./img/Samsung/Adapter_capsac/Adapter Sạc Type C 15W Samsung EP-T1510N.jpg', GETDATE(), GETDATE()),
(N'Pin sạc dự phòng 10000mAh không dây', N'Pin sạc dự phòng 10000mAh Không dây Magnetic Type C PD QC 3.0 20W Anker MagGo A1641', 1750000, 210, N'Adapter, cáp sạc', N'./img/Anker/Sac_Du_Phong/Pin sạc dự phòng 10000mAh Không dây Magnetic Type C PD QC 3.0 20W Anker MagGo A1641.jpg', GETDATE(), GETDATE());
GO